apiVersion: v1
kind: Secret
metadata:
  name: urbanx-secrets
  namespace: urbanx
type: Opaque
stringData:
  POSTGRES_PASSWORD: "<set-secure-password>"
  ConnectionStrings__identitydb: "Host=postgres;Database=urbanx_identity;Username=postgres;Password=<set-secure-password>"
  ConnectionStrings__catalogdb: "Host=postgres;Database=urbanx_catalog;Username=postgres;Password=<set-secure-password>"
  ConnectionStrings__orderdb: "Host=postgres;Database=urbanx_order;Username=postgres;Password=<set-secure-password>"
  ConnectionStrings__paymentdb: "Host=postgres;Database=urbanx_payment;Username=postgres;Password=<set-secure-password>"
  ConnectionStrings__merchantdb: "Host=postgres;Database=urbanx_merchant;Username=postgres;Password=<set-secure-password>"
  ConnectionStrings__inventorydb: "Host=postgres;Database=urbanx_inventory;Username=postgres;Password=<set-secure-password>"
